FROM node:22-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run prisma:gen && npm run build

FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=deps /app/node_modules node_modules
COPY --from=builder /app/dist dist
COPY --from=builder /app/node_modules/.prisma node_modules/.prisma
COPY prisma prisma
COPY package.json ./
RUN npx prisma generate
EXPOSE 3000
CMD ["node", "dist/server.js"]